--EZMANAGE_
create PROCEDURE [dbo].[SP_BACKUP_ADDITIONAL_FILES]
-- Old name: EZME_BACKUP_ADDITIONAL_FILES
 @DATABASE_NAME NVARCHAR(128),
 @SOURCE_PATH NVARCHAR(1024),
 @DEST_PATH NVARCHAR(3200),
 @FILENAME_SUFFIX NVARCHAR(80)
--WITH ENCRYPTION
AS
 if (@FILENAME_SUFFIX is null) set @FILENAME_SUFFIX = N''
SET NOCOUNT ON 

DECLARE @DEST_FILENAME NVARCHAR(1200)
DECLARE @DATABASE_FILENAME NVARCHAR(128)

IF (@SOURCE_PATH IS NULL) OR (@SOURCE_PATH = N'') RAISERROR(N'Source path is invalid or empty', 16, 1)
IF (@DEST_PATH IS NULL) OR (@DEST_PATH = N'')
BEGIN
 SELECT TOP 1 @DEST_PATH = [default_backup_folder] FROM EZManagePro..ET_Server_Settings
 IF (@DEST_PATH IS NULL) OR (@DEST_PATH = N'')
 BEGIN
  CREATE TABLE #tblFixedDrives (
   [drive] NVARCHAR(20),
   [FreeSpace] INT
  )
  INSERT INTO #tblFixedDrives EXEC master..xp_fixeddrives
  SELECT TOP 1 @DEST_PATH = [drive] FROM #tblFixedDrives
  IF (@DEST_PATH IS NULL) OR (@DEST_PATH = N'') RAISERROR(N'Destination path is invalid or empty', 16, 1)
  SET @DEST_PATH = @DEST_PATH+N':\EZManageSQL\AdditionalFiles\'
  DROP TABLE #tblFixedDrives
 END
END

IF RIGHT(@DEST_PATH, 1) != N'\' SET @DEST_PATH = @DEST_PATH+N'\'
SET @DATABASE_FILENAME = @DATABASE_NAME
IF CHARINDEX(N':\', @DATABASE_FILENAME) != 0 SET @DATABASE_FILENAME = REVERSE(SUBSTRING(REVERSE(@DATABASE_FILENAME), 0, CHARINDEX(N'\', REVERSE(@DATABASE_FILENAME))))
IF CHARINDEX(N'.mdf', @DATABASE_FILENAME) != 0 SET @DATABASE_FILENAME = REPLACE(@DATABASE_FILENAME, N'.mdf', N'')
IF CHARINDEX(N'.ldf', UPPER(@DATABASE_FILENAME)) != 0 SET @DATABASE_FILENAME = REPLACE(@DATABASE_FILENAME, N'.ldf', N'')
IF CHARINDEX(N'.ndf', UPPER(@DATABASE_FILENAME)) != 0 SET @DATABASE_FILENAME = REPLACE(@DATABASE_FILENAME, N'.ndf', N'')
SET @DATABASE_FILENAME = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(@DATABASE_FILENAME, N'\', N'$'), N':', N''), N'/', N'$'), N':', N'$'), N'*', N'$'), N'?', N'$'), N'"', N''''), N'<', N'('), N'>', N')'), N'|', N'$')
SET @DEST_FILENAME = REPLACE(CAST(SERVERPROPERTY(N'ServerName') AS NVARCHAR(256)), N'\', N'$')+N'_'+@DATABASE_FILENAME+N'_'+CONVERT(NVARCHAR(30), GETDATE(), 112)+N'_'+LEFT(REPLACE(CONVERT(NVARCHAR(80), GETDATE(), 108), N':', N''), 4)+N'_FILES'
IF (@FILENAME_SUFFIX IS NOT NULL) AND (@FILENAME_SUFFIX != N'') SET @DEST_FILENAME = @DEST_FILENAME+N'_'+@FILENAME_SUFFIX
SET @DEST_FILENAME = @DEST_FILENAME+N'.sqmf'

SET @DEST_PATH = @DEST_PATH+@DEST_FILENAME
PRINT(N'Backup files from "'+@SOURCE_PATH+N'" to file "'+@DEST_PATH+'"')
EXEC master..xp_sql_compress_folder @SOURCE_PATH, @DEST_PATH, '*.*', 1, 1