--EZMANAGE_
create PROCEDURE [dbo].[SP_BACKUP_POT_AVAILABLE] 
-- old name: EP_POT_AVAILABLE
 @DB_NAME NVARCHAR(128)
--WITH ENCRYPTION
AS

CREATE TABLE #tblPOT (
 time_start datetime,
 time_finish datetime
)

DECLARE @BACKUP_FINISH_DATE DATETIME
DECLARE @BACKUP_TYPE CHAR
DECLARE @TIME_START DATETIME
DECLARE @TIME_FINISH DATETIME
DECLARE @STARTED BIT
SET @STARTED = 0

DECLARE CUR CURSOR LOCAL FORWARD_ONLY READ_ONLY
FOR

SELECT 
bkset.backup_finish_date,
bkset.type
FROM
msdb..backupset bkset
INNER JOIN
msdb..backupmediafamily bkfam
	ON bkset.media_set_id = bkfam.media_set_id
WHERE
bkset.database_name = @DB_NAME AND
bkset.type IN (N'D', N'L')
ORDER BY
bkset.backup_finish_date ASC

OPEN CUR
FETCH NEXT FROM CUR INTO @BACKUP_FINISH_DATE, @BACKUP_TYPE
WHILE @@FETCH_STATUS = 0
BEGIN

IF @BACKUP_TYPE = N'D'
BEGIN
 IF @STARTED = 1
 BEGIN
  INSERT INTO #tblPOT (time_start, time_finish) VALUES (@TIME_START, @TIME_FINISH)
  SET @STARTED = 0
 END
 SET @TIME_START = @BACKUP_FINISH_DATE
 SET @TIME_FINISH = @BACKUP_FINISH_DATE
END
 ELSE
BEGIN
 IF @BACKUP_TYPE = N'L'
 BEGIN
  IF @TIME_START IS NOT NULL
  BEGIN
   SET @TIME_FINISH = @BACKUP_FINISH_DATE
   SET @STARTED = 1
  END
 END
END

FETCH NEXT FROM CUR INTO @BACKUP_FINISH_DATE, @BACKUP_TYPE
END

IF @STARTED = 1
BEGIN
 INSERT INTO #tblPOT (time_start, time_finish) VALUES (@TIME_START, @TIME_FINISH)
END

CLOSE CUR
DEALLOCATE CUR

SELECT * FROM #tblPOT ORDER BY time_finish DESC